servers:
  knowledge:
    type: local

  github:
    type: process
    command: "node"
    args:
      - "C:\\nvm4w\\nodejs\\node_modules\\@modelcontextprotocol\\server-github\\dist\\index.js"
    env:
      GITHUB_PERSONAL_ACCESS_TOKEN: "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"


  mlflow:
    type: process
    command: "C:\\Users\\Yugendra\\AppData\\Local\\pypoetry\\Cache\\virtualenvs\\driftguard-probe-igDHpR6t-py3.13\\Scripts\\python.exe"
    args:
      - "-m"
      - "mlflow"
      - "mcp"
      - "run"
    env:
      MLFLOW_TRACKING_URI: "http://localhost:5000"
