"""initial_schema

Revision ID: 65101e577c22
Revises: 
Create Date: 2026-07-29 09:47:48.390327

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65101e577c22'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('event_name', sa.String(length=100), nullable=False),
    sa.Column('actor', sa.String(length=100), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_event_name'), 'audit_logs', ['event_name'], unique=False)
    op.create_index(op.f('ix_audit_logs_investigation_id'), 'audit_logs', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('incident_id', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('final_root_cause', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('investigation_context', sa.JSON(), nullable=True),
    sa.Column('remediation_plan', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigations_id'), 'investigations', ['id'], unique=False)
    op.create_index(op.f('ix_investigations_incident_id'), 'investigations', ['incident_id'], unique=False)
    op.create_index(op.f('ix_investigations_investigation_id'), 'investigations', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_investigations_model_id'), 'investigations', ['model_id'], unique=False)
    op.create_index(op.f('ix_investigations_session_id'), 'investigations', ['session_id'], unique=True)
    op.create_index(op.f('ix_investigations_started_at'), 'investigations', ['started_at'], unique=False)
    op.create_index(op.f('ix_investigations_status'), 'investigations', ['status'], unique=False)
    op.create_table('mcp_servers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=False),
    sa.Column('transport', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.Column('last_health_check', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_servers_server_name'), 'mcp_servers', ['server_name'], unique=True)
    op.create_table('mcp_tools',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_tools_server_name'), 'mcp_tools', ['server_name'], unique=False)
    op.create_index(op.f('ix_mcp_tools_tool_name'), 'mcp_tools', ['tool_name'], unique=False)
    op.create_table('agent_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('prompt_version', sa.String(length=50), nullable=False),
    sa.Column('llm_model', sa.String(length=100), nullable=False),
    sa.Column('prompt_tokens', sa.Integer(), nullable=False),
    sa.Column('completion_tokens', sa.Integer(), nullable=False),
    sa.Column('total_tokens', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_executions_agent_name'), 'agent_executions', ['agent_name'], unique=False)
    op.create_index(op.f('ix_agent_executions_investigation_id'), 'agent_executions', ['investigation_id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('best_hypothesis_id', sa.String(length=100), nullable=False),
    sa.Column('recommended_actions_json', sa.JSON(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_best_hypothesis_id'), 'evaluations', ['best_hypothesis_id'], unique=False)
    op.create_index(op.f('ix_evaluations_investigation_id'), 'evaluations', ['investigation_id'], unique=True)
    op.create_table('evidence_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evidence_id', sa.String(length=100), nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('source_provider', sa.String(length=100), nullable=False),
    sa.Column('evidence_type', sa.String(length=100), nullable=False),
    sa.Column('capability', sa.String(length=100), nullable=False),
    sa.Column('server', sa.String(length=100), nullable=False),
    sa.Column('tool', sa.String(length=100), nullable=False),
    sa.Column('transport', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('raw_json', sa.JSON(), nullable=False),
    sa.Column('confidence_weight', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_items_evidence_id'), 'evidence_items', ['evidence_id'], unique=True)
    op.create_index(op.f('ix_evidence_items_evidence_type'), 'evidence_items', ['evidence_type'], unique=False)
    op.create_index(op.f('ix_evidence_items_investigation_id'), 'evidence_items', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_evidence_items_source_provider'), 'evidence_items', ['source_provider'], unique=False)
    op.create_index(op.f('ix_evidence_items_timestamp'), 'evidence_items', ['timestamp'], unique=False)
    op.create_table('evidence_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('goal', sa.Text(), nullable=False),
    sa.Column('capabilities_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_plans_investigation_id'), 'evidence_plans', ['investigation_id'], unique=True)
    op.create_table('hypotheses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('hypothesis_id', sa.String(length=100), nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detailed_reasoning', sa.Text(), nullable=False),
    sa.Column('supporting_evidence_ids', sa.JSON(), nullable=False),
    sa.Column('likelihood_score', sa.Float(), nullable=False),
    sa.Column('verified_by_simulation', sa.Boolean(), nullable=False),
    sa.Column('weaknesses', sa.JSON(), nullable=False),
    sa.Column('ranking', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_hypothesis_id'), 'hypotheses', ['hypothesis_id'], unique=True)
    op.create_index(op.f('ix_hypotheses_investigation_id'), 'hypotheses', ['investigation_id'], unique=False)
    op.create_table('investigation_memory',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('model_id', sa.String(length=100), nullable=False),
    sa.Column('problem_signature', sa.Text(), nullable=False),
    sa.Column('resolution', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('evidence_ids', sa.JSON(), nullable=False),
    sa.Column('runbooks_used', sa.JSON(), nullable=False),
    sa.Column('git_commit_hash', sa.String(length=100), nullable=False),
    sa.Column('mlflow_run_id', sa.String(length=100), nullable=False),
    sa.Column('outcome', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_investigation_memory_investigation_id'), 'investigation_memory', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_investigation_memory_model_id'), 'investigation_memory', ['model_id'], unique=False)
    op.create_table('knowledge_references',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('document_id', sa.String(length=100), nullable=False),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('referenced_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_references_document_id'), 'knowledge_references', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_references_investigation_id'), 'knowledge_references', ['investigation_id'], unique=False)
    op.create_table('mcp_executions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('server_name', sa.String(length=100), nullable=False),
    sa.Column('tool_name', sa.String(length=100), nullable=False),
    sa.Column('request_json', sa.JSON(), nullable=False),
    sa.Column('response_json', sa.JSON(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('finished_at', sa.DateTime(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mcp_executions_correlation_id'), 'mcp_executions', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_mcp_executions_investigation_id'), 'mcp_executions', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_mcp_executions_server_name'), 'mcp_executions', ['server_name'], unique=False)
    op.create_index(op.f('ix_mcp_executions_status'), 'mcp_executions', ['status'], unique=False)
    op.create_index(op.f('ix_mcp_executions_tool_name'), 'mcp_executions', ['tool_name'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('report_id', sa.String(length=100), nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('primary_root_cause', sa.String(length=200), nullable=False),
    sa.Column('markdown_content', sa.Text(), nullable=False),
    sa.Column('html_content', sa.Text(), nullable=True),
    sa.Column('json_content', sa.JSON(), nullable=False),
    sa.Column('generation_timestamp', sa.DateTime(), nullable=False),
    sa.Column('report_version', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_investigation_id'), 'reports', ['investigation_id'], unique=True)
    op.create_index(op.f('ix_reports_report_id'), 'reports', ['report_id'], unique=True)
    op.create_table('timeline_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('investigation_id', sa.String(length=100), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('stage', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_timeline_events_event_type'), 'timeline_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_timeline_events_investigation_id'), 'timeline_events', ['investigation_id'], unique=False)
    op.create_index(op.f('ix_timeline_events_stage'), 'timeline_events', ['stage'], unique=False)
    op.create_index(op.f('ix_timeline_events_timestamp'), 'timeline_events', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_timeline_events_timestamp'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_stage'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_investigation_id'), table_name='timeline_events')
    op.drop_index(op.f('ix_timeline_events_event_type'), table_name='timeline_events')
    op.drop_table('timeline_events')
    op.drop_index(op.f('ix_reports_report_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_investigation_id'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_mcp_executions_tool_name'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_status'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_server_name'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_investigation_id'), table_name='mcp_executions')
    op.drop_index(op.f('ix_mcp_executions_correlation_id'), table_name='mcp_executions')
    op.drop_table('mcp_executions')
    op.drop_index(op.f('ix_knowledge_references_investigation_id'), table_name='knowledge_references')
    op.drop_index(op.f('ix_knowledge_references_document_id'), table_name='knowledge_references')
    op.drop_table('knowledge_references')
    op.drop_index(op.f('ix_investigation_memory_model_id'), table_name='investigation_memory')
    op.drop_index(op.f('ix_investigation_memory_investigation_id'), table_name='investigation_memory')
    op.drop_table('investigation_memory')
    op.drop_index(op.f('ix_hypotheses_investigation_id'), table_name='hypotheses')
    op.drop_index(op.f('ix_hypotheses_hypothesis_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_evidence_plans_investigation_id'), table_name='evidence_plans')
    op.drop_table('evidence_plans')
    op.drop_index(op.f('ix_evidence_items_timestamp'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_source_provider'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_investigation_id'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_type'), table_name='evidence_items')
    op.drop_index(op.f('ix_evidence_items_evidence_id'), table_name='evidence_items')
    op.drop_table('evidence_items')
    op.drop_index(op.f('ix_evaluations_investigation_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_best_hypothesis_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_agent_executions_investigation_id'), table_name='agent_executions')
    op.drop_index(op.f('ix_agent_executions_agent_name'), table_name='agent_executions')
    op.drop_table('agent_executions')
    op.drop_index(op.f('ix_mcp_tools_tool_name'), table_name='mcp_tools')
    op.drop_index(op.f('ix_mcp_tools_server_name'), table_name='mcp_tools')
    op.drop_table('mcp_tools')
    op.drop_index(op.f('ix_mcp_servers_server_name'), table_name='mcp_servers')
    op.drop_table('mcp_servers')
    op.drop_index(op.f('ix_investigations_status'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_started_at'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_session_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_model_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_investigation_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_incident_id'), table_name='investigations')
    op.drop_index(op.f('ix_investigations_id'), table_name='investigations')
    op.drop_table('investigations')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_investigation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_name'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
