apiVersion: v1
kind: Service
metadata:
  name: driftguard-api-active
  namespace: driftguard
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: driftguard-api
---
apiVersion: v1
kind: Service
metadata:
  name: driftguard-api-canary
  namespace: driftguard
spec:
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
      name: http
  selector:
    app: driftguard-api
