"""Investigation state and reports query endpoints."""
from typing import List, Optional
from pydantic import BaseModel, Field
from fastapi import APIRouter, Depends, HTTPException, status
from ...schemas.api import APIResponse
from ...storage.session_repository import get_session_repository, SessionRepository

router = APIRouter(prefix="/api/v1/investigations", tags=["investigations"])


class InvestigationSummary(BaseModel):
    """Clean, dashboard-friendly metadata for a single investigation."""
    id: str = Field(..., description="Investigation session ID")
    status: str = Field(..., description="Lifecycle status e.g. completed, running, failed")
    model: str = Field(..., description="Target model name")
    severity: str = Field(..., description="Anomaly severity tier")
    confidence: float = Field(..., description="Diagnostic certainty score (0.0 to 1.0)")
    started_at: str = Field(..., description="ISO 8601 creation timestamp")
    completed_at: Optional[str] = Field(default=None, description="ISO 8601 completion timestamp")


@router.get("", response_model=APIResponse, summary="List active and historical investigations")
async def list_investigations(
    limit: int = 20,
    skip: int = 0,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve clean, dashboard-friendly summaries of all recorded investigations."""
    if hasattr(session_repo, "_storage"):
        sessions = list(session_repo._storage.values())
        items = []
        for s in sessions[skip:skip+limit]:
            conf = 0.85
            if s.evaluation_result:
                conf = s.evaluation_result.confidence
            elif s.hypotheses:
                conf = s.hypotheses[0].likelihood_score

            items.append(
                InvestigationSummary(
                    id=s.session_id,
                    status=s.status.value.lower(),
                    model=s.incident.model_id,
                    severity=s.incident.severity.value.lower(),
                    confidence=conf,
                    started_at=s.started_at.isoformat(),
                    completed_at=s.completed_at.isoformat() if s.completed_at else None
                ).model_dump(mode="json")
            )
        total = len(sessions)
    else:
        items = []
        total = 0
    return APIResponse(status="success", data={"total": total, "limit": limit, "skip": skip, "items": items})


@router.get("/{investigation_id}", response_model=APIResponse, summary="Get investigation details and executive report")
async def get_investigation_details(
    investigation_id: str,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve full lifecycle execution state, tested hypotheses, and compiled markdown report."""
    session = await session_repo.get(investigation_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Investigation '{investigation_id}' not found."
        )
    return APIResponse(
        status="success",
        data=session.model_dump(mode="json")
    )


@router.get("/{investigation_id}/timeline", response_model=APIResponse, summary="Get investigation execution timeline")
async def get_investigation_timeline(
    investigation_id: str,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve step-by-step agent execution durations and outcomes."""
    session = await session_repo.get(investigation_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Investigation '{investigation_id}' not found."
        )
    
    timeline_data = []
    # Add initial received event
    timeline_data.append({
        "agent": "Webhook Ingestion",
        "status": "completed",
        "started_at": session.started_at.isoformat(),
        "finished_at": session.started_at.isoformat(),
        "duration_ms": 10
    })
    
    for res in session.agent_results:
        timeline_data.append({
            "agent": res.agent_name,
            "status": "completed" if res.success else "failed",
            "started_at": res.started_at.isoformat(),
            "finished_at": res.finished_at.isoformat(),
            "duration_ms": int(res.latency * 1000)
        })
        
    return APIResponse(
        status="success",
        data={"timeline": timeline_data}
    )


@router.get("/{investigation_id}/evidence", response_model=APIResponse, summary="Get investigation evidence")
async def get_investigation_evidence(
    investigation_id: str,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve universal evidence collections generated by Investigator agent."""
    session = await session_repo.get(investigation_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Investigation '{investigation_id}' not found."
        )
    return APIResponse(
        status="success",
        data={
            "universal_evidence": [ev.model_dump(mode="json") for ev in session.universal_evidence],
            "legacy_evidence": [ev.model_dump(mode="json") for ev in session.evidence_items]
        }
    )


@router.get("/{investigation_id}/hypotheses", response_model=APIResponse, summary="Get investigation hypotheses")
async def get_investigation_hypotheses(
    investigation_id: str,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve causal root-cause hypotheses synthesized by Hypothesis agent."""
    session = await session_repo.get(investigation_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Investigation '{investigation_id}' not found."
        )
    return APIResponse(
        status="success",
        data={"hypotheses": [h.model_dump(mode="json") for h in session.hypotheses]}
    )


@router.get("/{investigation_id}/evaluation", response_model=APIResponse, summary="Get investigation evaluation")
async def get_investigation_evaluation(
    investigation_id: str,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve comparative hypothesis evaluations and recommendations generated by Evaluator agent."""
    session = await session_repo.get(investigation_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Investigation '{investigation_id}' not found."
        )
    return APIResponse(
        status="success",
        data={"evaluation_result": session.evaluation_result.model_dump(mode="json") if session.evaluation_result else None}
    )


@router.get("/{investigation_id}/report", response_model=APIResponse, summary="Get compiled investigation report")
async def get_investigation_report(
    investigation_id: str,
    session_repo: SessionRepository = Depends(get_session_repository)
) -> APIResponse:
    """Retrieve markdown executive report synthesized by Reporter agent."""
    session = await session_repo.get(investigation_id)
    if not session:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail=f"Investigation '{investigation_id}' not found."
        )
    return APIResponse(
        status="success",
        data={"report": session.report.model_dump(mode="json") if session.report else None}
    )
